name: LuckyWars
main: LuckyWars\LuckyWars
author: Jonas229
version: 1.0.0
api: [3.0.0-ALPHA1, 2.0.0]

commands:
    lw:
        usage: /lw <leave-make>
        description: LuckyWars-Commands
    lwstart:
        usage: /lwstart
        description: LuckyWars-Force start
